#!/usr/bin/env bash


readLines(){
	

	while read -r line; do
	
		if [[ $line == *"$2"* ]]; then
			echo -e "$1 \n $line \n\n\n" >> results.txt
		fi
	done <$1

}



for file in $(find "$1")
	do
		if [[ -f "$file" ]]; then
			readLines "$file" "$2"
		elif [[ -d "$file" ]]; then
			echo "Skipped - $file is a directory"
		fi;
	
	done;
